apiVersion: v1
kind: Service
metadata:
  labels:
    name: tomcat8
  name: tomcat8
spec:
  ports:
    # the port that this service should serve on
    - port: 8083
      targetPort: 8080
      nodePort: 30001
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: tomcat8
  type: NodePort
